### ISSUE TITLE
Error in build

### ISSUE THREAD

**Issue by mehdiraized** [saeedrahimi/antd-jalali#4]
nextjs v9.4.4
react 16.13.1
```
/node_modules/antd-jalali/dist/index.js:1
export { default as DatePicker } from "./DatePicker";
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
```

**Comment by TrueMoein** [comment]
Same issue...

**Comment by saeedrahimi** [comment]
I've just updated the library and fixed some issues.
Could you check it please?
